# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('doman', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=18)),
                ('e_mail', models.EmailField(max_length=254)),
                ('service', models.ManyToManyField(to='Hosts.Service')),
            ],
        ),
        migrations.AddField(
            model_name='hosts',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hosts.Service'),
        ),
    ]
