# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(max_length=32, verbose_name='请求时间')),
                ('ip', models.CharField(max_length=32, verbose_name='请求ip')),
                ('sn_addr', models.CharField(max_length=64, verbose_name='盒子地址')),
                ('channel', models.CharField(max_length=32, verbose_name='频道名')),
                ('stream', models.CharField(max_length=32, verbose_name='请求码流')),
                ('request_addr', models.CharField(max_length=32, verbose_name='请求节点')),
                ('sn', models.CharField(max_length=32, verbose_name='盒子号')),
                ('ht', models.BooleanField(verbose_name='是否启用超线程')),
                ('status', models.CharField(max_length=12, verbose_name='请求状态码')),
                ('down_time', models.CharField(max_length=12, verbose_name='本次下载时间')),
                ('ts_num', models.CharField(max_length=32, verbose_name='ts号')),
                ('netspeed', models.CharField(max_length=12, verbose_name='网速')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
