# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxinfo',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='请求时间'),
        ),
    ]
