# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxInfo', '0003_auto_20171016_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxinfo',
            name='request_time',
            field=models.DateTimeField(auto_now=True, verbose_name='请求时间'),
        ),
    ]
