# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_id',
            new_name='publish',
        ),
    ]
